apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-backup-config
data:
  POSTGRES_HOST: <"POSTGRES_HOST">
  POSTGRES_PORT: <"POSTGRES_PORT">
  POSTGRES_USER: <"POSTGRES_USER">
  POSTGRES_PASSWORD: <"POSTGRES_PASSWORD">
  DB_NAME: <"DB_NAME">
  VERBOSE: <"False">
  ACCESS_KEY: <"ACCESS_KEY">
  SECRET_KEY: <"SECRET_KEY">
  BUCKET_NAME: <"BUCKET_NAME">
  S3_ENDPOINT: <"S3_ENDPOINT">

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup-cron
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgres-backup
            image: <"DOCKER_IMAGE">
            imagePullPolicy: Always
            envFrom:
              - configMapRef:
                  name: postgres-backup-config
          restartPolicy: OnFailure